// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7GpimGP4VA1kMQVHrCgxDQVuA2rAe7GE',
    appId: '1:391296051839:web:e6f5bdd89b088942eded4a',
    messagingSenderId: '391296051839',
    projectId: 'iqra-foundation-bgp',
    authDomain: 'iqra-foundation-bgp.firebaseapp.com',
    databaseURL: 'https://iqra-foundation-bgp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iqra-foundation-bgp.firebasestorage.app',
    measurementId: 'G-2RPCWNWKWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGL7PQbtTDsT4VYKbhtwXR_XQkFYeC9vA',
    appId: '1:391296051839:android:f64b4fdccf711da4eded4a',
    messagingSenderId: '391296051839',
    projectId: 'iqra-foundation-bgp',
    databaseURL: 'https://iqra-foundation-bgp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iqra-foundation-bgp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwz7xtUps1DZXHrd2fqXpNIyaoiLPneag',
    appId: '1:391296051839:ios:c9d3e6c78cbbe74ceded4a',
    messagingSenderId: '391296051839',
    projectId: 'iqra-foundation-bgp',
    databaseURL: 'https://iqra-foundation-bgp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iqra-foundation-bgp.firebasestorage.app',
    androidClientId: '391296051839-ufcu8onqq5t2lphr3al7ece0hqaa6pfj.apps.googleusercontent.com',
    iosClientId: '391296051839-ra0mt1k4s9r2m7lot8hdl54jc2k8667v.apps.googleusercontent.com',
    iosBundleId: 'com.inFamous.iqra',
  );

}